### ISSUE TITLE
Add examples of using version ranges

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/setup-opa#7]
It currently says "see below", but there aren't any examples provided of using version ranges when fetching OPA. As these might not be familiar to people outside of the Node/NPM world, this would be a good addition to the README.

**Comment by srenatus** [comment]
https://github.com/open-policy-agent/setup-opa#inputs

> `version`: Optional, defaults to latest. SemVer ranges are supported, so instead of a full version string, you can use 0.35. This enables you to automatically get the latest backward compatible changes in the v0.35 release.

I think that section is meant. It contains a link to https://www.npmjs.com/package/semver#ranges. But you're looking for a copy-pastable snippet, I guess?

**Comment by anderseknert** [comment]
Indeed, some examples using a fixed version, a fixed major version and maybe one for latest/edge.
