### ISSUE TITLE
Publish to GitHub marketplace

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/setup-opa#9]
In order to improve the visibility of this project, it would be great if we published it to the GitHub Actions marketplace.

**Comment by srenatus** [comment]
![image](https://user-images.githubusercontent.com/870638/150985978-6fd7c06c-fee5-459b-b601-a90fac00a1f0.png)


Drafting a release yields this ☝️ We'll need to get that out of the way first, I suppose.

**Comment by tim775** [comment]
@tsandall can you "accept the GitHub Marketplace Developer Agreement" for the open-policy-agent org when you get a chance?

**Comment by Dal-Papa** [comment]
> @tsandall can you "accept the GitHub Marketplace Developer Agreement" for the open-policy-agent org when you get a chance?

Hi team ! Quick bump on this, it would give this action more visibility when searching on the marketplace.

**Comment by tsandall** [comment]
OK, it should be signed now.

**Comment by tim775** [comment]
It's published.  I'll ask around about how to get it set up with a proper OPA logo.
